[CLD-6378]Add lambdas to data engineeing
mattermost/mattermost-cloud-lambdas pull request #17
Opened 2023-09-27 19:18 UTC by andrleite

#### Summary
Add lambdas to data engineering env
#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/CLD-6327

2023-09-27 20:46 UTC, angeloskyratzakos approved these changes

2023-09-28 06:12 UTC, stafot approved these changes
LGTM

2023-09-28 06:14 UTC, stafot requested changes
Need to create `upload-data-eng-lambdas` job. Please refactore accordingly to be environment separated

2023-09-28 07:34 UTC, stylianosrigas requested changes
Just a minor ;)

2023-09-28 07:34 UTC, stylianosrigas commented on .github/workflows/data-engineering.yml
> +  upload-prod-lambdas:
```suggestion
  upload-data-engineering-lambdas:
```

2023-09-28 12:00 UTC, andrleite commented
> Need to create `upload-data-eng-lambdas` job. Please refactore accordingly to be environment separated

@stafot Sorry I didn't get it. What do you mean?

2023-09-28 12:38 UTC, stafot commented
@andrleite is the one you fixed already. Also you need to change the naming to be similar to other environments. (As `dev-ci.yaml` this should be `data-engineering-ci.yaml`

2023-09-28 12:59 UTC, stafot approved these changes

2023-09-28 13:57 UTC, stylianosrigas approved these changes

2023-09-28 13:58 UTC, merged